name = "ank"
description = "End-to-end encrypted email using the JMAP and Signal protocols"
version = "0.0.0"

authors = ["Oliver Mussell"]
maintainers = ["Oliver Mussell <oliver.mussell@hotmail.co.uk>"]
maintainers-logins = ["omussell"]

executables = ["ank"]

[[depends-on]]  # This line was added by `alr with`
sparknacl = "^2.0.0"  # This line was added by `alr with`
