site_name: "ANK"
site_url: "https://omussell.github.io/ank"
docs_dir: "site"
site_dir: "docs"
theme:
  name: "material"
  palette:
    primary: teal
  icon:
    logo: octicons/mention-16
  favicon: images/mention.svg

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.superfences
