site_name: "ANK"
site_url: "https://omussell.github.io/ank"

theme:
  name: "material"
  palette:
    primary: teal
  icon:
    logo: octicons/mention-16
  favicon: images/mention.svg

nav:
  - Home: index.md
  - Why: why.md
  - Client: client.md
  - Server: server.md
  - Key Transparency: key_transparency.md

plugins:
  - search

#markdown_extensions:
#  - toc:
#      permalink: True
#  - admonition
#  - pymdownx.superfences
